### PR TITLE
Replaced PhpExcel with PhpSpreadsheet

### PR DESCRIPTION
**Pull request by devOp1**
PhpExcel is replaced with PhpSpreadsheet to make yii2-excelexport php8.0 ready. Looking forward for a new version with this PR included.

### CODE REVIEW

**Comment by mikehaertl** [comment]
@devOp1 Thanks for the contribution. I currently have no time to have a closer look.

Did you test that everything still works? I'm actually surprised that there were so little changes. I always thought this would require some bigger refactoring.

In any case the README should also be updated.

Related issue: #24

**Comment by devOp1** [comment]
@mikehaertl I tested it with a large generated excel with several worksheet. For converting the code i used the rector script from https://phpspreadsheet.readthedocs.io/en/latest/topics/migration-from-PHPExcel/. I am not 100% sure if i configured composer correctly and would like to test that after merging.

**Comment by mikehaertl** [comment]
@devOp1 Ok, then it's probably fine. Could also go through the README and update the relevant parts (changed class names, link to PHPExcel, maybe update the example to handle styling etc.)? Then I'll merge and create a new release.

**Comment by mikehaertl** [comment]
@devOp1 Sorry, I forgot a "you" in the question above 😄 . Could *you* go through the README ...?

Otherwhise I can't promise when I will find time to do it. But I want to keep the README up to date before a release.

**Comment by devOp1** [comment]
@mikehaertl Done.

**Comment by mikehaertl** [comment]
@devOp1 Do you need a release or can you do some more testing first?

**Comment by devOp1** [comment]
I can test without a specific release. Thanks

**Comment by mikehaertl** [comment]
Cool. Please report back if everything works.

**Comment by devOp1** [comment]
It's working so far. But i will keep my eyes open.

**Comment by mikehaertl** [comment]
Ok, I think it's safe to create a release. We can still fix things in a later bugfix release.

Thanks for your help!

**Pull request merged**
