### PR TITLE
fixes using with null data export issues, team.name bug

### PR DESCRIPTION
**Pull request by liulipeng**
fixes using with null data export issues, team.name bug

code

```
    protected function renderRow($data, $row, $formats, $formatters, $callbacks, $types)
    {
        $values = array_map(function ($attr) use ($data) {
            return $data->getAttribute($attr);    //The value can not be here team.name
        }, $this->getAttributes());
        return parent::renderRow($values, $row, $formats, $formatters, $callbacks, $types);
    }
```

### CODE REVIEW

**Comment by mikehaertl** [comment]
Hmm, your solution only supports a single level. How about using [ArrayHelper::getValue()](http://www.yiiframework.com/doc-2.0/yii-helpers-basearrayhelper.html#getValue%28%29-detail) instead? It can also handle things like `team.address.street` and deal with non-existing values.

Would that also solve your problem? The implementation should be very simple. We just need to replace one line:

```
return ArrayHelper::getValue($data, $attr);
```

**Comment by liulipeng** [comment]
You are right！ 👍👍👍  hope the next version fixes Oh!

**Comment by mikehaertl** [comment]
@liulipeng I have pushed a change to master. Could you help testing this please? I currently have no time for it.

**Comment by liulipeng** [comment]
OK, I can help test tomorrow

**Comment by mikehaertl** [comment]
Great. I'll prepare a new release after your feedback.

Note though, that this feature is not really complete yet: The extension does not load labels and date formatters for related attributes. I'll add a note about this to the readme.

**Comment by liulipeng** [comment]
Passed the test, you can normally export this format x.y.z

The extension can load labels and date formatters for related attributes

This is my test case

```
        $file = \Yii::createObject([
            'class' => 'codemix\excelexport\ExcelFile',

            'writer' => '\PHPExcel_Writer_Excel5', // Override default of `\PHPExcel_Writer_Excel2007`

            'sheets' => [

                'Active Users' => [
                    'class' => 'codemix\excelexport\ActiveExcelSheet',
                    'query' => $query,

                    // If not specified, all attributes from `User::attributes()` are used
                    'attributes' => [
                        'id',
                        'name',
                        'subcategory.category.name',
                        'subcategory.category.created_at',
                        'category.name',
                        'subcategory.name',
                        'created_at',
                    ],
                    'formats' => [
                        // Either column name or 0-based column index can be used
//                        'D' => '#,##0.00',
                        3 => 'yyyy-mm-dd hh:mm:ss',
                        6 => 'yyyy-mm-dd hh:mm:ss',
                    ],
                    'formatters' => [
                        3 => function ($value, $row, $data) {
                            return \PHPExcel_Shared_Date::PHPToExcel($value);
                        },
                        6 => function ($value, $row, $data) {
                            return \PHPExcel_Shared_Date::PHPToExcel($value);
                        },
                    ],
                ],

            ],
        ]);

        $file->send('demo.xlsx');
```

**Comment by mikehaertl** [comment]
@liulipeng What happens if you don't define `formats` and `formatters` for the related columns? I assume, you get an exception then.

**Comment by mikehaertl** [comment]
Never mind, it seems I already implemented it :D 
https://github.com/codemix/yii2-excelexport/blob/master/src/ActiveExcelSheet.php#L243

**Pull request closed without merging**
